#
# EXAMPLE1:
# Load in 1 data source. Plot one forecast field from one
# lead time. Illustrates how the color maps are handled.
#
data:
  1:
    tmpl: local_fa_pl
    exp:  ["cy49_spp_p01"]
    ensm: [0]
    flds: ["CLSTEMPERATURE"]

times:
  sdate: 2025072412
  lead_times: 24

grid:
  subgrid:
  regrid:

opts:
  fig_name: "fig/example1.png"
  fig_size: [12,4,300] # [width,heigh,dpi]

# plot:
#   row1:
#     column1:
#       ...
#     column2:
#       ...
#   row2:
#     column1:
#       ...
#     column2:
#       ...
plot:
  1:
    1:
      type: "fc"
      data1: 1
      ensm: [0]
      name: 
      col_map: 
    2:
      type: "fc"
      data1: 1
      ensm: [0]
      name: 
      col_map: 1
    3:
      type: "fc"
      data1: 1
      ensm: [0]
      name: 
      col_map: 2

col_maps:
  1:
    name: "t2m_warm"
  2:
    name: "t2m_warm"
    breaks: "seq(10,35,5)"
