#
# EXAMPLE4:
# Also MEPS and Arome-Arctic data can be fetched directly
# from met.no thredds-server. grid:regrid:true is used
# to regrid data sources that are valid for different
# domains to data:1: grid.
#
data:
  1:
    tmpl: local_fa_pl
    exp:  ["cy46_spp_p01"]
    ensm: [0]
    flds: ["SURFTEMPERATURE"]
  2:
    tmpl: local_fa_pl
    exp:  ["cy46_spp_p01_fix2"]
    ensm: [0]
    flds: ["SURFTEMPERATURE"]
  3:
    tmpl: meps_oper
    exp: ["meps"]
    ensm: [0]
    flds: ["t2m"]
  4: NULL
  5:

times:
  sdate: 2025072412
  lead_times: 24

grid:
  subgrid: [300,738,200,600]
  regrid: true

opts:
  fig_name: "fig/example4.png"
  fig_size: [15,10,300] # [width,heigh,dpi]

# plot:
#   row1:
#     column1:
#       ...
#     column2:
#       ...
#   row2:
#     column1:
#       ...
#     column2:
#       ...
plot:
  1:
    1:
      type: "fc"
      data1: 1
      ensm: [0]
      name: "c46_"
      col_map: 1
    2: 
      type: "fc"
      data1: 2
      ensm: [0]
      name: "c46f_"
      col_map: 1
    3: 
      type: "diff"
      data1: 2
      data2: 1
      ensm: [0]
      name: "diff"
      col_map: 2
    4: NULL
  2:
    1:
      type: "diff"
      data1: 3
      data2: 1
      ensm: [0]
      name: "diff"
      col_map: 2
    2:
      type: "diff"
      data1: 3
      data2: 2
      ensm: [0]
      name: "diff"
      col_map: 2
    3:
      type: "fc"
      data1: 3
      ensm: [0]
      name: "meps_"
      col_map: 1
    4: NULL
  3: NULL

col_maps:
  1:
    name: "t2m_warm"
  2:
    name: "diff"
    breaks: "seq(-10,10,2)"
  3: NULL
