#
# EXAMPLE5:
# Forecasts from DEODE/Tactus runs can be also plotted
# in the exact same way. Note that you can either
# specify a different file_path here, or change it
# to the "common" yaml config file.
#
data:
  1:
    tmpl: local_fa_ml
    file_path: "/ec/scratch/fi3/investigation/deode_spp"
    exp:  ["de_fin_5SPP_bnd_9km"]
    ensm: [0,1]
    flds: ["SURFACCPLUIE"]
  2:
    tmpl: meps_oper
    exp: ["meps"]
    ensm: [0]
    flds: ["precipitation_amount_acc"]

times:
  sdate: 2024082600
  lead_times: 36

grid:
  subgrid: 
  regrid: true

opts:
  fig_name: "fig/example5.png"
  fig_size: [15,10,300] # [width,heigh,dpi]
  
# plot:
#   row1:
#     column1:
#       ...
#     column2:
#       ...
#   row2:
#     column1:
#       ...
#     column2:
#       ...
plot:
  1:
    1:
      type: "fc"
      data1: 1
      ensm: [0]
      name: "deod0"
      col_map: 1
    2: 
      type: "fc"
      data1: 1
      ensm: [1]
      name: "deod1"
      col_map: 1
    3: 
      type: "fc"
      data1: 2
      ensm: [0]
      name: "meps"
      col_map: 1
  2:
    1:
      type: "diff"
      data1: 1
      data2: 1
      ensm: [0,1]
      name: "diff"
      col_map: 2
    2:
      type: "diff"
      data1: 2
      data2: 1
      ensm: [0]
      name: "diff"
      col_map: 2

col_maps:
  1:
    name: "precip15"
  2:
    name: "diff"



